version: "3.4"

services:
  elasticsearch:
    image: elasticsearch:7.12.1
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  elasticsearch_hq:
    image: elastichq/elasticsearch-hq
    container_name: elasticsearch_hq
    depends_on:
      - elasticsearch
    environment:
      - "HQ_DEFAULT_URL=http://elasticsearch:9200"
    ports:
      - 5000:5000
    networks:
      - elastic

volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge
